# Generated by Django 5.0.6 on 2024-07-12 16:51

import apps.addresses.models
import apps.choices.lands
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('land', models.CharField(choices=apps.choices.lands.Lands.choices, max_length=25)),
                ('city', models.CharField(max_length=50)),
                ('street', models.CharField(max_length=100)),
                ('house_number', models.CharField(max_length=10)),
                ('postal_code', models.CharField(max_length=5, validators=[apps.addresses.models.validate_postal_code])),
            ],
        ),
    ]
